In [13]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from dataset import ConlluDataset
from DeepBiaffine import DeepBiaffineDependencyParser

max_len = 64
batch_size = 32

dataset = ConlluDataset('SUD_English-EWT/en_ewt-sud-dev.conllu', max_len=max_len)

word_ids, pos_ids, arc_labels, rel_labels = dataset[0]
word_ids = word_ids.unsqueeze(0)
pos_ids = pos_ids.unsqueeze(0)
arc_labels = arc_labels.unsqueeze(0)
rel_labels = rel_labels.unsqueeze(0)

print(arc_labels)

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         [1., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


In [45]:
vocab_size = len(dataset.word_2_index)
pos_size = len(dataset.pos_2_index)
embedding_dim = 256
lstm_hidden_size = 256
mlp_dim = 256
arc_out = 1
label_out = len(dataset.deprel_2_index)

model = DeepBiaffineDependencyParser(vocab_size, pos_size, embedding_dim, lstm_hidden_size, mlp_dim, arc_out, label_out)

arc_scores, rel_scores = model(word_ids, pos_ids)

print(arc_scores.argmax(dim=-1))
print(arc_labels.argmax(dim=-1))


tensor([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10,  6,  6, 10]])
tensor([[3, 2, 0, 0, 5, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])


In [46]:
a = {1, 2}
b = {2, 1}
a == b

True